theme: jekyll-theme-minimal

title: Cyclone V based latencybox
description: A DE0-nano-SoC latency measurement addon shield
logo: https://github.com/eurovibes/latbox_cycloneV/raw/master/images/latbox_cycloneV.png
show_downloads: true

github:
  zip_url: downloads/fabrication.zip
  tar_url: downloads/fabrication.tar.gz
